app = "chronologies-be"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  # Fly will build automatically with Docker if you have Dockerfile
  # or detect Node if no Dockerfile is present

[env]
  PORT = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
